version: 2

sources:
  - name: erp
    description: Banco réplica do erp da northwind.
    schema: erp_northwind
    tables:
      - name: orders
        description: Cada linha representa um pedido. Contém cancelados e deletados.
        columns:
          - name: order_id
            tests:
              - unique
              - not_null

      - name: categories
        description: Categorias de produtos vendidos pela northwind.
        columns:
          - name: category_id
            description: chave primária
            tests:
              - unique
              - not_null
